# Features best binned with q=2 (binary split)
high_cardinality_features_q2 = [
    
]

# Features best binned with q=3 (ternary split)
high_cardinality_features_q3 = [
    "dnf_rate_x_practice_std",
    "positions_gained_first_lap_pct",
    "grid_penalty_x_constructor",
    "qual_x_constructor_wins",
    "practice_x_safetycar",
    "recent_form_x_qual",
    "practice_improvement_vs_teammate",
    "qual_improvement_vs_teammate",
    "races_with_constructor",


    "practice_consistency_vs_teammate",
    "practice_consistency_vs_constructor_historical",
    "qualifying_consistency_vs_constructor_historical",
    "practice_position_vs_teammate_historical",
    "qualifying_position_vs_teammate_historical",
    "practice_position_percentile_vs_constructor",
    "qualifying_position_percentile_vs_constructor",
    "practice_position_vs_constructor_median_at_track",
    "practice_position_vs_field_median_at_track",
    "practice_position_vs_field_worst_at_track",
    "practice_position_vs_field_best_at_track",
    "practice_position_vs_constructor_best_at_track",
    "practice_position_vs_constructor_worst_at_track",
    "qualifying_position_vs_field_recent_form",
    "qualifying_position_vs_constructor_recent_form",
    "practice_position_vs_constructor_recent_form",
    "practice_position_vs_field_recent_form",
    "qualifying_position_vs_field_recent_form",
    "practice_position_std",
    "practice_consistency_std",
    "practice_improvement_vs_field_avg",
    "qual_improvement_vs_field_avg",
    "practice_improvement_rate",
    "practice_to_qualifying_delta",
    "practice_to_qual_position_delta",
    "practice_to_qual_improvement_rate",
    "practice_to_qualifying_delta_vs_constructor_historical",
    "practice_lap_time_improvement_rate",
    "practice_lap_time_consistency_vs_field",
    "qualifying_lap_time_consistency_vs_field",
    "practice_lap_time_delta_to_constructor_best",
    "qualifying_lap_time_delta_to_constructor_best",
    "practice_improvement_vs_constructor_historical",
    "qualifying_improvement_vs_constructor_historical",
    "practice_consistency_vs_constructor_historical",
    "qualifying_consistency_vs_constructor_historical",
    "practice_gap_to_teammate",
    "qual_gap_to_teammate",
    "driver_teammate_practice_gap_3r",
    "driver_teammate_qual_gap_3r",
    "recent_vs_season",
    "recent_form_ratio",
    "constructor_form_ratio",
]

# Features best binned with q=5 (default, most continuous)
high_cardinality_features_q5 = [
    "dnf_rate_x_practice_std",
    "positions_gained_first_lap_pct",
    "grid_penalty_x_constructor",
    "qual_x_constructor_wins",
    "practice_x_safetycar",
    "recent_form_x_qual",
    "practice_improvement_vs_teammate",
    "qual_improvement_vs_teammate",
    "races_with_constructor",
    "LapTime_sec",
    "driverFastestPracticeLap_sec",
    "bestQualifyingTime_sec",
    "best_qual_time",
    "best_theory_lap_sec",
    "best_s3_sec",
    "delta_from_race_avg",
    "best_s2_sec",
    "best_s1_sec",
    "practice_qual_consistency_5r",
    "fp1_lap_delta_vs_best",
    "practice_lap_time_consistency_vs_field",
    "practice_lap_time_consistency",
    "grid_x_avg_pit_time",
    "pit_delta_x_driver_age",
    "Delta_FP2",
    "CleanAirAvg_FP2",
    "DirtyAirAvg_FP2",
    "Delta_FP1",
    "DirtyAirAvg_FP1",
    "CleanAirAvg_FP1",
    "teammate_qual_delta",
    "fp1_lap_time_delta_to_best",
    "teammate_practice_delta",
    "practice_time_improvement_1T_2T",
    "qual_lap_time_consistency",
    "practice_lap_time_delta_to_constructor_best",
    "practice_time_improvement_2T_3T",
    "practice_time_improvement_time_time",
    "practice_time_improvement_1T_3T",
    "last_race_vs_track_avg",
    "DirtyAirAvg_FP3",
    "CleanAirAvg_FP3",
    "Delta_FP3",
    "BestConstructorPracticeLap_sec",
    "teammate_practice_delta_at_track",
    "constructor_qual_consistency_5r",
    "historical_avgLapPace",
    "historical_race_pace_vs_median",
    "practice_position_vs_field_recent_form",
    "driver_teammate_practice_gap_3r",
    "practice_improvement_vs_field",
    "fp3_vs_constructor_avg",
    "constructor_recent_x_track_exp",
    "constructor_practice_improvement_3r",
    "average_practice_x_driver_podiums",
    "grid_position_percentile",
    "driver_practice_improvement_3r",
    "power_to_corner_ratio",
    "top_speed_x_turns",
    "qualifying_position_percentile",
    "qualPos_x_avg_practicePos",
    "fp3_position_percentile",
    "practice_position_vs_constructor_median_at_track",
    "practice_position_vs_field_median_at_track",
    "driver_avg_practice_pos_at_track",
    "practice_vs_track_median",
    "constructor_avg_practice_pos_at_track",
    "practice_vs_best_at_track",
    "avg_final_position_per_track",
    "avg_final_position_per_track_constructor",
    "practice_vs_worst_at_track",
    "track_fp1_fp3_improvement",
    "constructor_avg_qual_pos_at_track",
    "constructor_avg_grid_pos_at_track",
    "qualifying_position_vs_constructor_recent_form",
    "constructor_avg_practice_position",
    "SpeedFL_mph",
    "practice_improvement_x_qual",
    "SpeedI2_mph",
    "SpeedI1_mph",
    "practice_position_vs_field_worst_at_track",
    "practice_to_qualifying_delta",
    "practice_to_qual_position_delta",
    "constructor_points_x_grid",
    "recent_form_5_races",
    "practice_position_vs_field_best_at_track",
    "driver_positionsGained_5_races",
    "qualPos_x_last_practicePos",
    "constructor_recent_form_5_races",
    "driver_avg_qual_pos_at_track",
    "driver_avg_grid_pos_at_track",
    "driver_starting_position_5_races",
    "practice_position_std",
    "practice_consistency_std",
    "overtake_potential_5yr",
    "SpeedST_mph",
    "overtake_potential_3yr",
    "qual_to_final_delta_5yr",
    "qual_to_final_delta_3yr",
    "top_speed_rank",
    "grid_x_constructor_rank",
    "total_experience",
    "averagePracticePosition",
    "driver_positionsGained_3_races",
    "recent_positions_gained_3_races",
    "driver_constructor_avg_qual_position",
    "driver_constructor_avg_final_position",
    "constructor_recent_form_3_races",
    "recent_form_3_races",
    "driver_starting_position_3_races",
    "qualifying_position_vs_constructor_median_at_track",
    "driver_qual_improvement_3r",
    "constructor_qual_improvement_3r",
    "qual_vs_track_avg",
    "practice_std_x_qual",
    "qual_vs_constructor_avg_at_track",
    "constructor_practice_improvement_rate",
    "qual_vs_constructor_avg",
]

# Features best binned with q=10+ (very wide range, only if you have lots of data)
high_cardinality_features_q10plus = [
    "LapTime_sec",
    "bestQualifyingTime_sec",
    "practice_lap_time_consistency",
    "historical_avgLapPace",
    "avg_final_position_per_track",
    "practice_position_percentile_vs_constructor",
    
]

# Combined list for use in raceAnalysis.py
high_cardinality_features = (
    high_cardinality_features_q2 +
    high_cardinality_features_q3 +
    high_cardinality_features_q5 +
    high_cardinality_features_q10plus
)