import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
// Load pure modules as data URLs; the implementation is identical to the source files.
const root = new URL('../code/frontend/',import.meta.url);
const preferencesText = await readFile(new URL('preferences.js',root),'utf8');
const preferencesURL = 'data:text/javascript;base64,'+Buffer.from(preferencesText).toString('base64');
const preferences = await import(preferencesURL);
const clientText = (await readFile(new URL('viewClient.js',root),'utf8')).replace("'./preferences.js'",JSON.stringify(preferencesURL));
const {createViewClient} = await import('data:text/javascript;base64,'+Buffer.from(clientText).toString('base64'));
const storage = {value:null,getItem(){return this.value;},setItem(_key,value){this.value=value;}};
const values = {filter_results_main:true,range_filter_grandPrixYear:[2017,2026],filter_resultsDriverName:'Max Verstappen',f1bet_field_upload:{content:'private'},bankroll:10000};
preferences.savePreset('Recent seasons',2,values,storage);
assert.equal(preferences.readPresets(storage)[0].values.f1bet_field_upload,undefined);
assert.equal(preferences.readPresets(storage)[0].values.bankroll,undefined);
const url = preferences.shareUrl(2,values,'http://localhost/#/Analytics');
assert.deepEqual(preferences.readSharedView(new URL(url).hash).values,preferences.safeValues(values));
assert.throws(() => preferences.validateView({version:99,page:1}));
assert.equal(preferences.hasUpload({f1bet_field_upload:'csv'}),true);
let revision = 'r1', posts = 0;
const fetcher = async url => {
  if(url.endsWith('/status'))return {ok:true,json:async() => ({revision})};
  posts++; await new Promise(resolve => setTimeout(resolve,10));
  return {ok:true,json:async() => ({nodes:[],value:posts})};
};
const client = createViewClient({fetcher});
const payload = {page:1,values:{year:2026}};
await Promise.all([client.load(payload,{enabled:true}),client.load(payload,{enabled:true})]);
assert.equal(posts,1,'Identical requests must share one API post');
await client.load(payload,{enabled:true});assert.equal(posts,1);
revision = 'r2';await client.load(payload,{enabled:true});assert.equal(posts,2);
await client.load({...payload,action:'explicit'},{enabled:true});assert.equal(posts,3);
await client.load(payload,{enabled:true});assert.equal(posts,4,'Actions must invalidate retained views');
const cancelled = new AbortController();cancelled.abort();
await assert.rejects(client.load(payload,{signal:cancelled.signal}),{name:'AbortError'});
const tiny = createViewClient({fetcher,maxBytes:1});
await tiny.load(payload,{enabled:true});assert.equal(tiny.retainedBytes(),0);
const timeoutClient = createViewClient({normalTimeout:5,fetcher:(_url,{signal}) => new Promise((_resolve,reject) => signal.addEventListener('abort',() => reject(new DOMException('Cancelled','AbortError'))))});
await assert.rejects(timeoutClient.load(payload),/timed out/);
console.log('Frontend proposal contracts passed: presets, share links, privacy, request deduplication, revision invalidation, actions, cancellation and cache budget.');
