"""
compute_teammate_delta.py
-------------------------
Patches data_files/all_qualifying_races.csv with two derived columns that
fastF1-qualifying.py produces during a live data pull but that may be absent
or incomplete when the CSV was generated by an older version of the script:

  best_qual_time   -- fastest timed lap in seconds for the driver that session
                      (min of Q1_sec, Q2_sec, Q3_sec; falls back to actual_best_lap)
  teammate_qual_delta -- driver's best_qual_time minus the mean of their
                         team-mates' best_qual_time (same logic as
                         add_teammate_delta() in fastF1-qualifying.py)

The script always:
  1. Fills any null best_qual_time values from actual_best_lap (or Q-session cols)
  2. Recomputes teammate_qual_delta from scratch to fix groups degraded by nulls

Run standalone:
    python scripts/compute_teammate_delta.py

Exit codes: 0 = success (or nothing to do), 1 = error.
"""

import sys
import traceback
from pathlib import Path

import pandas as pd

SCRIPT_DIR  = Path(__file__).resolve().parent
REPO_ROOT   = SCRIPT_DIR.parent
QUAL_CSV    = REPO_ROOT / "data_files" / "all_qualifying_races.csv"

GROUPBY_COLS = ["Year", "Round", "constructor_group"]


# ---------------------------------------------------------------------------
# Helper: replicate add_teammate_delta() from fastF1-qualifying.py
# ---------------------------------------------------------------------------
def add_teammate_delta(df: pd.DataFrame,
                       group_cols: list,
                       value_col: str,
                       new_col: str) -> pd.DataFrame:
    """Return df with new_col = value_col minus mean of team-mates (same group)."""
    vals = pd.to_numeric(df[value_col], errors="coerce")
    team_count = df.groupby(group_cols)[value_col].transform(
        lambda s: pd.to_numeric(s, errors="coerce").notna().sum()
    )
    team_sum = df.groupby(group_cols)[value_col].transform(
        lambda s: pd.to_numeric(s, errors="coerce").fillna(0).sum()
    )
    # mean of OTHER drivers in the same group (exclude self)
    other_mean = (team_sum - vals) / (team_count - 1)
    df = df.copy()
    df[new_col] = vals - other_mean
    return df


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    if not QUAL_CSV.exists():
        print(f"SKIP: qualifying CSV not found at {QUAL_CSV}")
        return 0

    try:
        df = pd.read_csv(QUAL_CSV, sep="\t", low_memory=False)
    except Exception as exc:
        print(f"ERROR: could not read {QUAL_CSV}: {exc}")
        return 1

    print(f"Loaded {QUAL_CSV.name}: {len(df):,} rows, {len(df.columns)} cols")

    needs_write = False

    # ── 1. best_qual_time: create or fill nulls ──────────────────────────────
    # Build the best fallback time: Q-session mins, then actual_best_lap
    time_cols = [c for c in ("Q1_sec", "Q2_sec", "Q3_sec") if c in df.columns]
    candidate: pd.Series | None = None
    if time_cols:
        q_min = df[time_cols].apply(pd.to_numeric, errors="coerce").min(axis=1)
        # Secondary fallback: fill remaining nulls from actual_best_lap
        if "actual_best_lap" in df.columns:
            alap = pd.to_numeric(df["actual_best_lap"], errors="coerce")
            candidate = q_min.where(q_min.notna(), alap)
        else:
            candidate = q_min
    elif "actual_best_lap" in df.columns:
        candidate = pd.to_numeric(df["actual_best_lap"], errors="coerce")

    if "best_qual_time" not in df.columns:
        if candidate is not None:
            df["best_qual_time"] = candidate
            print(f"  Created best_qual_time from {time_cols or ['actual_best_lap']}")
            needs_write = True
        else:
            print("WARN: no source columns found for best_qual_time -- skipping")
            return 0
    else:
        # Fill nulls from fallback so delta grouping isn't degraded when a
        # driver is missing Q1/Q2/Q3 but has an actual_best_lap value
        bqt = pd.to_numeric(df["best_qual_time"], errors="coerce")
        if candidate is not None:
            fill_mask = bqt.isna() & candidate.notna()
            if fill_mask.any():
                bqt = bqt.where(~fill_mask, candidate)
                df["best_qual_time"] = bqt
                print(f"  Filled {int(fill_mask.sum())} null best_qual_time values from fallback")
                needs_write = True
            else:
                print("  best_qual_time: no nulls to fill")
        else:
            print("  best_qual_time: present (no fallback columns available)")

    # ── 2. Build stable constructor group key ────────────────────────────────
    if "constructor_group" not in df.columns:
        if "constructorId" in df.columns:
            cname = df["constructorName"] if "constructorName" in df.columns else "unknown"
            df["constructor_group"] = df["constructorId"].fillna(cname).astype(str)
        elif "constructorName" in df.columns:
            df["constructor_group"] = df["constructorName"].astype(str)
        else:
            print("WARN: no constructor column found -- skipping teammate_qual_delta")
            if needs_write:
                df.to_csv(QUAL_CSV, sep="\t", index=False)
                print(f"  Saved {QUAL_CSV.name} (best_qual_time only)")
            return 0
        needs_write = True

    # ── 3. teammate_qual_delta: always recompute to fix null-polluted groups ─
    missing_gb = [c for c in GROUPBY_COLS if c not in df.columns]
    if missing_gb:
        print(f"WARN: missing groupby columns {missing_gb} -- skipping teammate_qual_delta")
    else:
        before_nnull = int(df["teammate_qual_delta"].notna().sum()) if "teammate_qual_delta" in df.columns else 0
        df = add_teammate_delta(
            df,
            group_cols=GROUPBY_COLS,
            value_col="best_qual_time",
            new_col="teammate_qual_delta",
        )
        after_nnull = int(df["teammate_qual_delta"].notna().sum())
        delta_gain = after_nnull - before_nnull
        print(f"  Recomputed teammate_qual_delta: {after_nnull:,} non-null rows "
              f"(+{delta_gain} vs before)")
        needs_write = True

    # ── 4. Save ──────────────────────────────────────────────────────────────
    if needs_write:
        try:
            df.to_csv(QUAL_CSV, sep="\t", index=False)
            print(f"  Saved {QUAL_CSV.name} ({len(df):,} rows)")
        except Exception as exc:
            print(f"ERROR: could not write {QUAL_CSV}: {exc}")
            traceback.print_exc()
            return 1
    else:
        print("  No changes needed.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
